# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:nestor-huma/specs.git'

target 'NewsPlugin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsPlugin
  pod 'PluginCore', '1.0.0'

end
